### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by FalcoSuessgott** [FalcoSuessgott/vkv#101]
* [x] new output format which shows the token policies recursive for each kv path using self-capabilities api call
* [x] cli flag for showing secrets version
* [x] cli flag for showing secrets metadata
* [ ] cli flag for showing the links to each secret
* [x] shell completion
* [x] man page
* [x] cli flag which lists all kv engines and use can interactively choose
* [x] cli flag for browsing through kv engines and on right side u see the tree view (maybe using something like bubbletea or fzf)
* [x] better github pages https://github.com/alex-shpak/hugo-book
* [x] create an icon
* [ ] add template snippet for generating the corresponding tf code that recreates the complete kv engine
* [x] harmonize gif images and font sizes
* [x] only build gifs when tag
* [x] test document behaviour with not sufficient token policy
* [x] always test against last 3 mayor versions
* [x] support KVv1
* [x] import command which takes vkv json or yaml output (flags: -f, -d, STDIN, --force, dry-run/preview)
* [x] Separate files in printer dir with tests
* [x] add commands for encrypting exported secrets with pgp and importing them again (decrypting)
* [x] Subcommand for mirroring secrets between two emgines in intervalls (daemon) takes a congig file
* [ ] Flag for showing previous secret versions
* [x] Warn if masked secrets are imported
* [ ] Handle Engine path in vkv import
* [x] encrypt/decrypt secrets using sops and vault
* [x] Vault backup subcommand (export alle kv engines from all visble ns, flags: namespace, list engines, …)
* [x] Vault restore - restores all exported kv engines
* [x] Docker & k8s cronjob integration
* [ ] #118
* [x] use conventional commits and group in changelog in goreleaser
* [x] quick start guide
* [x] write proper testutils (create/delete ns, engines, spinup vault, ...)
* [ ] usage with tf for secret importing without being in state
* [ ] List minimum required policy for all features
* [x] add custom metadata to markdown output
* [ ] switch to https://pkg.go.dev/github.com/hashicorp/vault/api#Client.KVv2 and https://pkg.go.dev/github.com/hashicorp/vault/api#Client.KVv1 and see if it is better
